# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

variables:
  patch1: $[counter(variables['build.reason'], 0)]
  name: patch_version
  value1: $[counter(format('{0}.{1}', variables['major_version'], variables['minor_version']), 1)]
  value21: $[counter(format('{0}.{1}.{2}', variables['major_version'], variables['minor_version'],variables['build.reason']), 1)]


pool:
  vmImage: 'ubuntu-latest'
  
steps:
  - bash: echo $(patch1)

  - bash: echo $(value1)
  - bash: echo $(value21)