# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

variables:
  patch: $[counter(variables['build.reason'], 0)]
  string: $[format('Hello {0} {1}', 'John', 'Doe')]
  name: patch_version
  value: $[counter(format('{0}.{1}', variables['major_version'], variables['minor_version']), 1)]

name: $(major_version).$(minor_version).$(patch_version)

pool:
  vmImage: 'ubuntu-latest'
  
steps:
  - bash: echo $(patch)
  - bash: echo $(string)
  - bash: echo $(value)